---
- name: Install prerequisite packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: Add Docker APT repo
  apt_repository:
    repo: "deb {{ docker_apt_repo }} {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
